name: github_traker_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.19.0
  freezed_annotation: ^2.4.1 # このままでOK (freezed本体とanalyzerが重要)
  json_annotation: ^4.9.0 # ★ここを ^4.9.0 またはそれ以上に更新！★
  go_router: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9 # このままでOK
  freezed: ^2.5.2 # このままでOK (freezed_annotation と対になるバージョン)
  json_serializable: ^6.7.1 # このままでOK
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
